<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">		
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
			<?php		
			$tabs = $block->getCustomTabs();			
			if(!empty($tabs)):?>			
				<?php foreach($tabs as $tab): ?>
					<div class="data item title" id="tab-label-<?php echo $tab['key']; ?>" data-role="collapsible" aria-labeledby="tab-label-<?php echo $tab['key']; ?>-title">
						<a class="data switch" tabindex="-1" data-toggle="switch" href="#<?php echo $tab['key']; ?>" id="tab-label-<?php echo $tab['key']; ?>-title"><?php echo $tab['tab_title']; ?></a>
					</div>
					<div class="data item content" id="<?php echo $tab['key']; ?>" data-role="content">
						<?php echo $tab['tab_content_attr']; ?>
						<?php echo $tab['tab_content_block']; ?>
					</div>
				<?php endforeach;?>
			<?php endif; ?>
        </div>
    </div>
<?php endif; ?>